name: Docker Image CI

env:
  DOCKER_IMAGE_NAME: wseresearch/loris-backend
  DOCKER_CONTAINER_NAME: loris-backend
  SERVICE_PORT: ${{ secrets.SERVICE_PORT }}
  SECURITY_HEADER_VALUE: ${{ secrets.SECURITY_HEADER_VALUE }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
  MONGO_PORT: ${{ secrets.MONGO_PORT }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
  MONGO_HOST: ${{ secrets.MONGO_HOST }}
  MISTRAL_ENDPOINT: ${{ secrets.MISTRAL_ENDPOINT }}

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Get current version
        run: >
          echo "X_APP_VERSION=$(cat < run.py | grep -Po '(?<=__version__ = \")([^\"]*)')" >> $GITHUB_ENV
      - name: Build the Docker image for deployment
        run: >
          docker build --tag "$DOCKER_IMAGE_NAME:latest" .
      - name: Tag image with specific version
        run: >
          docker tag "$DOCKER_IMAGE_NAME:latest" "$DOCKER_IMAGE_NAME:$X_APP_VERSION"
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push docker image with latest version
        run: docker push "$DOCKER_IMAGE_NAME:latest"
      - name: Push docker image with specific version
        run: docker push "$DOCKER_IMAGE_NAME:$X_APP_VERSION"
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: SSH into server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          envs: DOCKER_IMAGE_NAME,DOCKER_CONTAINER_NAME,SERVICE_PORT,SECURITY_HEADER_VALUE,OPENAI_API_KEY,MONGO_USERNAME,MONGO_PORT,MONGO_PASSWORD,MONGO_HOST,MISTRAL_ENDPOINT
          script: |
            docker stop "$DOCKER_CONTAINER_NAME" || true && docker rm -f "$DOCKER_CONTAINER_NAME" || true && docker image rm -f "$DOCKER_IMAGE_NAME:latest" || true
            echo "Pulling image: $DOCKER_IMAGE_NAME" 
            docker pull $DOCKER_IMAGE_NAME:latest
            echo "Starting container: $DOCKER_CONTAINER_NAME" 
            docker run --restart=always -d -p 8099:$SERVICE_PORT -e SECURITY_HEADER_VALUE=$SECURITY_HEADER_VALUE -e OPENAI_API_KEY=$OPENAI_API_KEY -e MONGO_USERNAME=$MONGO_USERNAME -e MONGO_PORT=$MONGO_PORT -e MONGO_PASSWORD=$MONGO_PASSWORD -e MONGO_HOST=$MONGO_HOST -e MISTRAL_ENDPOINT=$MISTRAL_ENDPOINT --name "$DOCKER_CONTAINER_NAME" "$DOCKER_IMAGE_NAME:latest"